### ISSUE TITLE
Crashes on server

### ISSUE THREAD

**Issue by coderbot16** [Zoutelande/GlintColor#4]
* Needs to be marked as "environment": "client" in fabric.mod.json

* Needs to use the "client" instead of "main" entrypoint and a ClientModInitializer instead of a ModInitializer

**Comment by Zoutelande** [comment]
Thanks a lot for this, I haven't had time to investigate so this really helped me out. I will fix it later today.

**Comment by coderbot16** [comment]
You're welcome! These are simple things but they're not exactly the most discoverable parts of fabric.

This will make sure that anyone using this cool mod in modpacks can safely place it in the server files without it being loaded accidentally as it is a client only mod
